In [2]:
# Array Broadcasting
# How NumPy treats arrays of unequal shapes
import numpy as np
x = np.array([[-0. , -0.1, -0.2, -0.3],
              [-0.4, -0.5, -0.6, -0.7],
              [-0.8, -0.9, -1. , -1.1]])
y = np.array([1, 2, 3, 4])
print(x * y) #y is multiplied by each row of x
#Basically replicates the row three times to be multiplied

x = np.array([[[0, 1]],
               [[2, 3]],
              [[4, 5]]])
y = np.array([[0],
              [1],
              [-1]])
print(x * y)  #Duplicates column to multiply across

#Broadcast-incompatible arrays
# np.array([1, 2]) * np.array([0, 1, 2])
# Because (2,) array cannot be duplicated to match with (3,)

[[-0.  -0.2 -0.6 -1.2]
 [-0.4 -1.  -1.8 -2.8]
 [-0.8 -1.8 -3.  -4.4]]
[[[ 0  0]
  [ 0  1]
  [ 0 -1]]

 [[ 0  0]
  [ 2  3]
  [-2 -3]]

 [[ 0  0]
  [ 4  5]
  [-4 -5]]]


In [3]:
#np.broadcast_to
x = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11]])
print(np.broadcast_to(x, (2,3,4))) #We can use this function to broadcast array to specific shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [4]:
# Excercise
# 7 x 2 with 7, incompatible
# 4 with 3 x 4, turns into 3 * 4
# 1 x 3 x 1 with 8 x 1 x 1, turns into 8 * 3 * 1
# 9 x 2 x 5 with 2 x 5, turns into 9 * 2 * 5
# 3 with 3 x 3 x 2, incompatible

In [5]:
#Application
#Each student has taken three exams
grades = np.array([[ 0.79,  0.84,  0.84],
                   [ 0.87,  0.93,  0.78],
                   [ 0.77,  1.00,  0.87],
                   [ 0.66,  0.75,  0.82],
                   [ 0.84,  0.89,  0.76],
                   [ 0.83,  0.71,  0.85]])
mean_exam_scores = grades.mean(axis=0)
mean_exam_scores = np.round(mean_exam_scores, 2)
print(mean_exam_scores) #finds mean socre for each exam

score_offset = np.zeros_like(grades)
for n, scores_per_student in enumerate(grades): #scores_per_student is a shape (3,) array for given student
    score_offset[n] = scores_per_student - mean_exam_scores
score_offset = grades - mean_exam_scores
print(score_offset) #Stores (score-mean) for each exam score

[0.79 0.85 0.82]
[[ 0.   -0.01  0.02]
 [ 0.08  0.08 -0.04]
 [-0.02  0.15  0.05]
 [-0.13 -0.1   0.  ]
 [ 0.05  0.04 -0.06]
 [ 0.04 -0.14  0.03]]


In [6]:
#Excercise
x = np.random.rand(10000,2)
center_of_mass = np.mean(x, axis = 0)
print(center_of_mass.shape)

relative_pos = x - center_of_mass
print(relative_pos.shape)

(2,)
(10000, 2)


In [7]:
#NewAxis and Size-1 axes
print(np.array([1,2,3]).reshape(1,3,1,1)) #(3, array into a (1,3,1,1))
#One stack of three sheets, each has one row and column
x = np.array([1,2,3])
y= x[np.newaxis, :, np.newaxis, np.newaxis] #newaxis adds new axes
print(y)
print(y.shape)


[[[[1]]

  [[2]]

  [[3]]]]
[[[[1]]

  [[2]]

  [[3]]]]
(1, 3, 1, 1)


In [8]:
#Size-1 dimensions for Broadcasting
x_1d = np.array([1,2,3])
x = x_1d.reshape(3,1)
print(x)
y = np.array([4,5,6,7])
print(x*y) #this result from the format of x (3,1) which is then multiplied by (4,)


[[1]
 [2]
 [3]]
[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]]


In [9]:
# Excercise 2
x = np.array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]],

              [[12, 13, 14, 15],
               [16, 17, 18, 19],
               [20, 21, 22, 23]]])
summed_rows = x.sum((axis = 2))
print(summed_rows)

norm = x / summed_rows[:, :,  np.newaxis]
norm.sum(axis = 2)

SyntaxError: invalid syntax (4254025099.py, line 9)

In [10]:
#Excercise 3
images=np.random.rand(500,48,48,3)
y = images.max(axis = (1,2))
print(y.shape)

norm_images = images / y.reshape(500,1,1,3)
print(norm_images.max(axis =(1,2)))
np.all(norm_images.max(axis=(1,2)) == 1)

(500, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 ...
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


True

In [11]:
#Advanced Application: Pairwise Distances
# Basically, the specific form of an equation can have a major impact on the memory-footprint
# of its vectorized implementation in NumPy. This issue can be overlooked.

In [26]:
images=np.random.rand(4,1,3,2)
images2=np.random.rand(1,1,1)
images - images2

array([[[[ 0.5324805 ,  0.18242591],
         [ 0.11624193,  0.54804971],
         [ 0.46239259, -0.08505468]]],


       [[[ 0.18543895, -0.06029977],
         [ 0.38156674,  0.30522537],
         [ 0.10354233,  0.65723834]]],


       [[[ 0.54889963,  0.40453364],
         [-0.01222668, -0.10304069],
         [-0.15575986,  0.05985804]]],


       [[[ 0.43922881,  0.36269468],
         [ 0.67997899, -0.17275274],
         [ 0.49214249, -0.12804665]]]])