In [2]:
import numpy as np
#Note
    #when accessing arrays, it goes from outside to inside (ex: [0,1,1])
    #
np.array(8) # 1D array
np.array([[93,  95],
          [84, 100],
          [99,  87]])  # 2D array
x = np.array([[[0,1],[2,3]], 
         [[4,5],[6,7]]]) #3D array
#0-based indices and slicing to access
print(x[0,:,::-1]) #sheet-0, both rows, flip order of columns

[[1 0]
 [3 2]]


In [23]:
#1D Array
oneD_array = np.array([2.3, 0.1, -9.1])
print(oneD_array[0])
print(oneD_array[-2])
print(oneD_array[1:3])


2.3
0.1
[ 0.1 -9.1]


In [35]:
#2D Array
grades = np.array([[93, 95], [84,100], [99,87]]) #a oneD array would not be ideal
print(grades.shape)
print(grades[1,0])
#Slice indexing
print(grades[0:3, 1]) #slice through all arrays and get the element at pos 1
print(grades[1:, 1]) #equivalent to grades[1:3, 1]
print(grades[:, :1]) #equivalent to grades [0:3, 0:1]
#Negative indices
print(grades[:, -1])

(3, 2)
84
[ 95 100  87]
[100  87]
[[93]
 [84]
 [99]]
[ 95 100  87]


In [39]:
#N-Dimensional Arrays
d3_array = np.array ([[[0,1],[2,3]], [[4,5],[6,7]]])
print(d3_array[0,1,0])
print(d3_array[:,0,0]) #Retrieve a 1d sub-array from a 3d-array
print(d3_array[1]) # also known as d3_array [1,:, :] / retrieve a 2d sub-array

2
[0 4]
[[4 5]
 [6 7]]


In [8]:
# Excercise
arr = np.array([[[ 0,  1,  2],
                 [ 3,  4,  5],
                 [ 6,  7,  8]],

                [[ 9, 10, 11],
                 [12, 13, 14],
                 [15, 16, 17]],

                [[18, 19, 20],
                 [21, 22, 23],
                 [24, 25, 26]]])
print(arr[:,:,2])
print(arr[0:2,1,:])
print(arr[:1,:2,2])
print(arr[1,:,::-1])

[[ 2  5  8]
 [11 14 17]
 [20 23 26]]
[[ 3  4  5]
 [12 13 14]]
[[2 5]]
[[11 10  9]
 [14 13 12]
 [17 16 15]]


In [84]:
#Zero dimensional arrays
x = np.array(15.2) #you cannot index in array
print(x.item()) #must use this syntax to retrieve numerical entry
#Don't show up in real applications

15.2


In [88]:
# Manipulating Arrays
x = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])
print(x.reshape(3,2,2))
print(x.transpose()) #Transpose reverses the ordering of its axes.

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [36]:
#Reshape
x = np.array([0,1,2,3,4,5])
print(x.reshape(2,3)) #Shapes the array into a (2[row],3[column]) array
print(np.array([0,1,2,3,4]).reshape(1,5)) #cannot split into (3,2) because 5 can't split (since 2,3 = 6)
print("------------")
#Reshaping a multidimensional array
y = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
print(y.reshape(2,3,2)) #Reshape from (3, 4) to (2, 3, 2)

[[0 1 2]
 [3 4 5]]
[[0 1 2 3 4]]
------------
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [15]:
# "Autofill", basically, you can have NumPy compute a dimension's size for you
# Use -1 for value you want
np.arange(36).reshape(3, 4, 3)   # (36,) --reshape--> (3, 4, 3)
np.arange(36).reshape(3, 4, -1)  # NumPy replaces -1 with 36/(3*4) -> 3
np.arange(36).reshape(3, -1, 3)  # NumPy replaces -1 with 36/(3*3) -> 4
np.arange(36).reshape(-1, 4, 3)  # NumPy replaces -1 with 36/(3*4) -> 3
#Only one dimension


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])