In [8]:
import numpy as np
print(np.array([i**2 for i in range(5)])) #creates array from sequence
print(np.ones((2,4))) #creates array of ones
print(np.linspace(0,10,5)) 
print(np.random.normal(1,5,10)) #samples 10 numbbers randomly from mean01, std-dev-5 normal
print(np.array([1.5,3.20,5.78], dtype=int)) #creates array from specified datatype


[ 0  1  4  9 16]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 0.   2.5  5.   7.5 10. ]
[ 7.78675123 -0.35075166  5.1570746   2.1641213  -7.58682586 -7.58516624
  6.71468973 -6.66255039  7.3779821   2.04858054]
[1 3 5]


In [16]:
#Creates array from Python Sequences
# You can create an array from list or tuple by using .array function
print(np.array([1.,2.,3.])) #shape: 3,
#list of lists of nums will produce 2d array
print(np.array([[1., 2., 3.], [4., 5., 6.]])) # shape: (2,3)
# A list of lists of lists of zeros create a 3d array
print(np.array([[[0]*4]*3]*2))

[1. 2. 3.]
[[1. 2. 3.]
 [4. 5. 6.]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [23]:
#Creating Constant Arrays: Zeros and ones
print(np.zeros((3,4))) # 3x4 array of zeros
#Create a shape-(4,) array of ones
print(np.ones((4,))) #Create a array of ones

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1.]


In [29]:
#Creating Sequential Array: arange and linspace
print(np.arange(0, 10, 1))  # start (included):0, stop (excluded):10,step:1
print(np.arange(10))  # start = 0, step= 1 are defaults
print(np.arange(-5, 6, 2))

#Linespace allows you to gernate N evenly-spaced points within interval
print(np.linspace(-1, 1, 5)) #makes five evenly-spaced points on the interval
print(np.linspace(-100,100, 5))
print(np.linspace(3,4,2)) #two evenly spaced pints on 3,4
print(np.linspace(-np.pi, np.pi, 100)) #lmao

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[-5 -3 -1  1  3  5]
[-1.  -0.5  0.   0.5  1. ]
[-100.  -50.    0.   50.  100.]
[3. 4.]
[-3.14159265 -3.07812614 -3.01465962 -2.9511931  -2.88772658 -2.82426006
 -2.76079354 -2.69732703 -2.63386051 -2.57039399 -2.50692747 -2.44346095
 -2.37999443 -2.31652792 -2.2530614  -2.18959488 -2.12612836 -2.06266184
 -1.99919533 -1.93572881 -1.87226229 -1.80879577 -1.74532925 -1.68186273
 -1.61839622 -1.5549297  -1.49146318 -1.42799666 -1.36453014 -1.30106362
 -1.23759711 -1.17413059 -1.11066407 -1.04719755 -0.98373103 -0.92026451
 -0.856798   -0.79333148 -0.72986496 -0.66639844 -0.60293192 -0.53946541
 -0.47599889 -0.41253237 -0.34906585 -0.28559933 -0.22213281 -0.1586663
 -0.09519978 -0.03173326  0.03173326  0.09519978  0.1586663   0.22213281
  0.28559933  0.34906585  0.41253237  0.47599889  0.53946541  0.60293192
  0.66639844  0.72986496  0.79333148  0.856798    0.92026451  0.98373103
  1.04719755  1.11066407  1.17413059  1.23759711  1.30106362  1.364

In [34]:
#Random sampling
rng = np.random.default_rng()
print(rng.random((3,3))) #entries randomly from [0,1)
print(rng.normal(size=(5,))) #Create a shape 5, array by drawing randomly
                            # from a mean-0, variance-1 Gaussian distribution

[[0.58112577 0.30812097 0.83495336]
 [0.23432606 0.24946403 0.63768462]
 [0.59162153 0.98906745 0.53105687]]
[ 0.25087824 -1.20481653  0.11333633 -0.3382475  -0.08424777]


In [42]:
#Specificed Data Type Array
print(np.array([1,2,3], dtype="float32"))
print(np.arange(0,4).dtype) #default is 64 bit ints
print(np.arange(0,4,dtype="float16")) #Data type produced by 'arange' can be specified otherwise
print(np.zeros((4,4),dtype="complex64"))


[1. 2. 3.]
int64
[0. 1. 2. 3.]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [54]:
#Joining Arrays Together
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])
print(np.vstack([x,y])) #Stacks vertically, makes another array and a array to encapsulate
#for vstack, both arrays must have same amount of columns
print(np.hstack([x,y])) #Stacks horizontally

[[ 1  2  3]
 [-1 -2 -3]]
[ 1  2  3 -1 -2 -3]


array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93