In [17]:
import numpy as np
print([i for i in enumerate("abcdef")]) #Enumeration for iterable

#ndenumerate function
x = np.array([[[ 25,   6, -35],
               [  9, -40, -29]],

              [[ -8,   2, -37],
               [ 17,  10, -45]]])
[i for i in np.ndenumerate(x)]#Enumerates each element in an ND array

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e'), (5, 'f')]


[((0, 0, 0), 25),
 ((0, 0, 1), 6),
 ((0, 0, 2), -35),
 ((0, 1, 0), 9),
 ((0, 1, 1), -40),
 ((0, 1, 2), -29),
 ((1, 0, 0), -8),
 ((1, 0, 1), 2),
 ((1, 0, 2), -37),
 ((1, 1, 0), 17),
 ((1, 1, 1), 10),
 ((1, 1, 2), -45)]

In [19]:
print(x[0,0,0])
print(x[0,0,1])
# Traversing Array: Row-major(C) vs Column-major(F) Traversal Ordering
#array([0, 1, 2, 3, 4, 5]).reshape(2, 3) -->  array([[0, 1, 2],  or   array([[0, 2, 4],
                                                  #  [3, 4, 5]])             [1, 3, 5]])
#NumPy always defaults to row-major ordering which is the first one that goes from (0,1..,5)
y = np.arange(10).reshape(5,2)
print(y)
print(y.reshape(10))

25
6
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]
