In [26]:
import numpy as np #as np allows us to abbreviate
x = np.array([0,1,2,3,4,5,6,7,8,]) #ND-array
print(type(x))
print(isinstance(x, np.ndarray))
x = x.reshape(3,3)
print(x)
print(np.power(x,2)) #utilize "vectorized" operations without need of for loop
print("")
print(np.mean(x, axis=1)) #mean of each row
print("")
print(x**np.array([0.,1.,2.])) #broadcasting to raise each column of x to diff power
print("")
print(x[:2, :3]) #first two rows, first three columns
print("")
x[x%2 ==0] *= -1 #change all even numbers to negative
print(x)

<class 'numpy.ndarray'>
True
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]

[1. 4. 7.]

[[ 1.  1.  4.]
 [ 1.  4. 25.]
 [ 1.  7. 64.]]

[[0 1 2]
 [3 4 5]]

[[ 0  1 -2]
 [ 3 -4  5]
 [-6  7 -8]]
