"Vectorized" Operations: Optimized Computations on NumyPt Arrays

In [5]:
#Basic Math Operations using Arrays
import numpy as np
x = np.array([[ 0.,  1.,  2.],
            [ 3.,  4.,  5.],
              [ 6.,  7.,  8.]])
print(x**2)
print(np.sqrt(x))
print(.5 + x[0, :])

[[ 0.  1.  4.]
 [ 9. 16. 25.]
 [36. 49. 64.]]
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]
[0.5 1.5 2.5]


In [45]:
y = np.array([[-4. , -3.5, -3. ],
              [-2.5, -2. , -1.5],
              [-1. , -0.5, -0. ]])
print(x+y)
print(x*y)

#Sequential Function, np.sum
x = x = np.array([[ 0.,  1.,  2.],
                  [ 3.,  4.,  5.],
                  [ 6.,  7.,  8.]])
print(np.sum(x))
print(np.sum(x, axis = 0)) #Summing over rows, within each column of array

[[-4.  -2.5 -1. ]
 [ 0.5  2.   3.5]
 [ 5.   6.5  8. ]]
[[-0.  -3.5 -6. ]
 [-7.5 -8.  -7.5]
 [-6.  -3.5 -0. ]]
36.0
[ 9. 12. 15.]


- ND Arrays are homogenous (array can only contain one data type)
- Lists and tuples are unrestricted
- NumPy does this to delegate mathematical operations to optimized C code
- This is known as **vectorization** (Basically describes the use of optimized, pre-compiled code written in a low-level language like C to perform operations)
    - Way faster than analogous computation performed in Python

In [46]:
import numpy as np
print(np.sum(np.arange(10000))) #takes around 11 microseconds
total = 0
for i in np.arange(10000): #Takes about 822 microseconds
    total = i + total   
print(total)

49995000
49995000


In [47]:
#Examples of vectorized function computations
print(2 * np.array([2,3,4])) #multiply 2 with each num in array
print(np.array([10.2, 3.5, -0.9]) - np.array([8.2,3.5,6.5])) #subtract two arrays
print(np.dot(np.array([1, -3, 4]), np.array([2, 0, 1]))) #Take dot product of two arrays
#Basically multiply their corresponding entries and sum result (1*2) + (-3*0) + (4*1) = 6

[4 6 8]
[ 2.   0.  -7.4]
6


NumPy's Mathematical Functions
- Unary functions: f(x)
- Binary functions: f(x,y)
- Functions that operate on sequences of numbers: f({x<sub>i</sub>})<sub>i=0</sub><sup>n-1</sup>

In [48]:
# Unary Functions (includes Trig, Log, and Exponential)
# Applies f(x) gto each element within the array
# **IT PRODUCES A NEW ARRAY AS A RESULT (input array is not overwritten)
x = np.array([0.,1.,2.])
y = np.array([10., 9., 16])
print(np.absolute(x)) # |x|
print(np.sqrt(x)) #sqrt(x)

[0. 1. 2.]
[0.         1.         1.41421356]


In [49]:
print(np.sin(x)) #sin x
print(np.cos(x)) #cos x
print(np.tan(x)) #tan x

[0.         0.84147098 0.90929743]
[ 1.          0.54030231 -0.41614684]
[ 0.          1.55740772 -2.18503986]


In [50]:
print(np.log(y)) # lnx
print(np.log10(y)) # log10 x
print(np.log2(y)) # log2 x
print(np.exp(y)) #e^x

[2.30258509 2.19722458 2.77258872]
[1.         0.95424251 1.20411998]
[3.32192809 3.169925   4.        ]
[2.20264658e+04 8.10308393e+03 8.88611052e+06]


In [57]:
x = np.array([[-1,2], [-3,4]])
print(x)
print(np.square(x)) # equivalent to 'x**2'
print(x[:, 0] **2) # square column-0 of x

[[-1  2]
 [-3  4]]
[[ 1  4]
 [ 9 16]]
[1 9]


In [23]:
# excercise
x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15]])
print(np.log(x[2,0::2]))
        # OR ***
y = np.log(x[2, 0])
z = np.log(x[2, 2])
print(np.hstack([y,z]))

[2.07944154 2.30258509]
[2.07944154 2.30258509]


In [37]:
# Binary Functions 
# f(x,y)
# we can still use standard math operators (+-*/) if both arrays are NumPy
# Calling it will call the NumPy function "under the hood", vectorized will still be used
x = np.array([0,3])
y = np.array([1,2])
#Main binary functions
print(np.multiply(x,y)) # x * y
print(np.divide(x,y)) # x / y
print(np.add(x,y)) #x + y
print(np.subtract(x,y)) # x - y
print(np.power(x,y)) # x ** y
print(np.mod(x,y)) # x % y
print()
#Some other common binary functions:
print(np.maximum(x,y)) # max (x,y)
print(np.minimum(x,y)) # min (x,y)

[0 6]
[0.  1.5]
[1 5]
[-1  1]
[0 9]
[0 1]

[1 3]
[0 2]


In [43]:
x = np.array([[10,  2],
              [ 3,  5]])

y = np.array([[ 1,   0],
              [ -4,  -1]])
print(x + y)
print(x[:,0] + y [1,:])

[[11  2]
 [-1  4]]
[6 2]


In [54]:
# Excercise 
x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15]])
print(x[:2,:2] + x[:2, 2:4] + x[2:4, :2] + x[2:4, 2:4])
print(x[:2,:2] + x[:2, -2:] + x[-2:, :2] + x[2:4, 2:4]) 

[[20 24]
 [36 40]]
[[20 24]
 [36 40]]


In [63]:
# Scalars and Arrays
print(3 * np.array([0., 1., 2.])) #Convenient calling for np.multiply(3,x)
print(np.array([1.,2.,3.]) ** 2) #Convenient calling for np.power(x,2)
x = np.array([[10,  2],
              [3,  5]])
print(np.maximum(4,x))
y = np.array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
               [ 8,  9, 10, 11, 12, 13, 14, 15]],

              [[16, 17, 18, 19, 20, 21, 22, 23],
               [24, 25, 26, 27, 28, 29, 30, 31]]])
print(y[0,:,::2] * -1)


[0. 3. 6.]
[1. 4. 9.]
[[10  4]
 [ 4  5]]
[[  0  -2  -4  -6]
 [ -8 -10 -12 -14]]


Sequential Functions
- f({x<sub>i</sub>})<sub>i=0</sub><sup>n-1</sup>
- Sequential function expects a variable length sequence of numbers for input
- Produces a single number as output

In [74]:
x = np.array([0.,3.,4.])
print(np.mean(x)) #x.mean()
print(np.median(x)) #x.median()
print(np.var(x)) #Variance (degree spread of data)
print(np.std(x)) #Std deviation
print(np.max(x)) # Differnet from np.max(x,y) [takes different num of vals]
print(np.min(x)) # Minimum val
print(np.argmax(x)) # Index of max value
print(np.argmin(x)) # Index of min value
print(np.sum(x)) # x.sum()

2.3333333333333335
3.0
2.8888888888888893
1.699673171197595
4.0
0.0
2
0
7.0


In [76]:
# Multi dimensional arrays and sequential functions
x = np.array([[0,1],
              [2,3],
              [4,5]])
np.sum(x) #Sum will treat multi-d array as a single sequence by default

15

In [102]:
# Specifying the axis Keyword Arg in sequential NumPy Fucntions
# creating a shape-(3,2) array
x = np.array([[0, 1],
              [2, 3],
              [4, 5]])
print(np.sum(x, axis = 0)) #Sum over axis-0 within axis-1, sums over rows within each column
print(np.sum(x, axis = 1)) #Sum over columns within each row

# negative axis-indices can be used too
print(np.sum(x, axis=-1))  # equivalent: np.sum(x, axis=1)

# sum over axis-0 and axis-1
# i.e. sum the array as if it were a 1D sequence (default behavior)
print(np.sum(x, axis=(0, 1)))  # equivalent: x.sum(axis=(0, 1))



[6 9]
[1 5 9]
[1 5 9]
15


In [111]:
x = np.arange(24).reshape(4,2,3)
print(x)
np.mean(x, axis = (0,2))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


array([10., 13.])

In [112]:
# Excercise
# 4D array of random numbers
images = np.random.rand(100, 32, 32, 3)

mean_imag = images.mean(axis=0)
print(mean_imag.shape)

print(images.sum())

min_blue = images[:, :, :, 2].min(axis=(1, 2))
print(min_blue.shape)

pixel_std_dev = images.std(axis=(0, 3))
print(pixel_std_dev.shape)

max_red_quad = images[:, :16, :16, 0].max(axis=(1, 2))
print(max_red_quad.shape)

(32, 32, 3)
153408.20539344082
(100,)
(32, 32)
(100,)


In [169]:
# AXES EXPLAINED BY ME, JACOB NG :DDDD
# Basically, this is very goofy
# I still don't really understand

images = np.random.rand(2, 3, 4, 5) #Shape is (2,3,4,5) ("stack, sheet, row, column")
print(images.mean(axis=(-2,-1))) #this essentially provides length of 2,3 since it finds the sums of the last two lengths (4,5)
#What the equation means is that it finds the mean of all numbers in rows and columns of x, for each sheet in stack
print(images.min()) #returns one value because it goes through all axes
print(images.std(axis=(0,1,3))) # This is one dimension because it finds the std of every other axis
print(np.sum(images, axis=(0,1))) #The axes of the value returned is (4,5) since we find the sum of (2,3)

[[0.43721893 0.55700938 0.53777203]
 [0.63252322 0.55126801 0.4513965 ]]
0.011226510147192004
[0.27498103 0.28095865 0.28125474 0.31746754]
[[2.94040053 3.68418677 3.22218446 3.3355425  4.29748227]
 [1.88452639 2.26313855 2.09543029 2.39683217 3.71435352]
 [3.09832395 3.46602226 4.12030294 4.02234905 2.45489297]
 [2.90625983 3.69950554 4.50554248 1.86096102 3.37552396]]
